### ISSUE TITLE
Extract the base implementation as a separate package.

### ISSUE THREAD

**Issue by gmosx** [dart-lang/json_rpc_2#1]
The base Server,Client,Peer,TwoWayStream etc classes would be useful to other projects. They could be extracted to a separate package and kinda get  standardized...

**Comment by nex3** [comment]
These classes are pretty specific to the nature of JSON-RPC 2; they explicitly encode the notions of method names, list/map parameter structures, batches, and so on. I'd be open to implementing a more generic notion of message channels if one becomes popular, but I don't think extracting one from this is the right way to go.
