### ISSUE TITLE
Input subscription is not canceled on `close()`

### ISSUE THREAD

**Issue by natebosch** [dart-lang/json_rpc_2#20]
If a `Peer` is closed the subscription on the input `Stream` is not canceled, so if it is listening on something coming from `stdin` or similar the process may never exit.

**Comment by nex3** [comment]
`Peer.close()` [calls `ChannelManager.close()`](https://github.com/dart-lang/json_rpc_2/blob/master/lib/src/peer.dart#L112), which in turn [calls `StreamChannel.sink.close()`](https://github.com/dart-lang/json_rpc_2/blob/master/lib/src/channel_manager.dart#L77). [The second `StreamChannel` guarantee](https://github.com/dart-lang/stream_channel/blob/7e551639f5f7149e5e2791e0247b85e5f0173f71/lib/stream_channel.dart#L41-L42) says that closing the sink closes the channel, which should cause `stdin` to close.

If this isn't working properly, I'd guess the stream channel you're passing in doesn't follow the guarantees. Make sure to create `StreamChannel`s using [`new StreamChannel.withGuarantees()`](https://www.dartdocs.org/documentation/stream_channel/1.6.1/stream_channel/StreamChannel/StreamChannel.withGuarantees.html) or [`StreamChannelController`](https://www.dartdocs.org/documentation/stream_channel/1.6.1/stream_channel/StreamChannelController-class.html) if you don't want to manually ensure that all guarantees are obeyed.
