### ISSUE TITLE
Let the Client also support regular HTTP connections

### ISSUE THREAD

**Issue by stevenroose** [dart-lang/json_rpc_2#3]
The Client implementation assumes an asynchronous connection (it requires a Stream of responses and a StreamSink for requests). This is ideal for WebSockets, but very hard to get working with regular HTTP connections (which JSONRPC2 also support).

Currently, I [hacked something](https://github.com/stevenroose/async_http/blob/master/lib/async_http.dart) to make regular HTTP requests mimic a WebSocket, but it's far from the ideal situation. I think the Client implementation should support both types of connections.

**Comment by nex3** [comment]
I'm not sure exactly what you're asking for. HTTP itself is asynchronous, so an asynchronous API seems appropriate for it. What sort of an API are you imagining?

**Comment by stevenroose** [comment]
A simple HTTP client is not asynchronous. It sends requests and expects exactly one response back that is linked to the request.
And so is the Dart HTTP client. It does not work asynchronously as it has a request method that returns the response in a Future. There is no way of capturing all HTTP messages from a certain server, which is required by the Client implementation of json_rpc_2.

F.e. the interface would look like this:
```dart
class JsonRpcClient {
  // The current default constructor, used for WebSockets
  JsonRpcClient.async(Stream<String> responses, StreamSink<String> requests);
  // A new constructor, used for regular HTTP clients
  // It basically takes as argument a function that takes a request and returns
  //   a future with the response value, like the dart:io.HTTPClient.post method.
  JsonRpcClient.sync(Future<String> doRequest(String request));
}

**Comment by nex3** [comment]
@stevenroose I think you and I are using different meanings of the idea of "asynchrony". What I mean is the way the Dart language and libraries use it: an operation that doesn't return its result as a return value but instead as a Future or Stream or callback that will produce that value at a later time. Anything using [`dart:async`](https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart:async) is async.

JSON-RPC 2's spec is structured around the idea of a two-way stream of information. It's possible to do this via HTTP, but if you're modeling each JSON-RPC request as a single HTTP request you run into friction: what does the client do if the server returns a response with a different id than the request's? What does the server do if the client sends a notification, which the spec says it must not reply to? The spec doesn't cover these issues, which means that the library shouldn't either. It's up to the person who's writing the code to convert the transport protocol into something the spec understands to make these decisions.

**Comment by stevenroose** [comment]
I understand that the JSON-RPC specification considers an HTTP connection as being asynchronous. And I also know that HTTP is in fact an asynchronous protocol.

What I'm talking about the the use of your implementation in actual Dart code. Few JSON-RPC endpoints are WebSocket-complient and thus require communication over regular HTTP. I challenge you to implement a working server proxy using the dart:io library and your client implementation.

As a library published by the official Dart team, I think usability is just as important as theoretical correctness.

**Comment by nex3** [comment]
This library implements a spec. We can't just make decisions about the protocol that aren't covered by the spec; we have to leave those up to the user, or we'll lose interoperability. The reasons you're finding it challenging to massage the HTTP library's API to fit this package's API are the same reasons that it's not easy to massage JSON-RPC 2.0 into working over HTTP in the first place.

Out of curiosity, can you give me a few examples of JSON-RPC endpoints that don't support WebSocket?

**Comment by stevenroose** [comment]
Why? The spec does not require a JSON-RPC 2.0 endpoint to support WebSockets, as JSON-RPC 2.0 is transport agnostic by design.

About JSON-RPC 2.0 being hard to use over HTTP, why? Since 2.0 there is a clear client-server separation, meaning that every client->server message will cause exactly 0 or 1 server->client messages. Isn't that exactly how HTTP works?

Besides, let me repeat it again: I'm not asking you to break with the spec, I'm just asking you to make the library useful.

**Comment by nex3** [comment]
> Why? The spec does not require a JSON-RPC 2.0 endpoint to support WebSockets, as JSON-RPC 2.0 is transport agnostic by design.

As is this library. It takes an abstract stream for requests and an abstract sink for responses, which are the same abstract structures JSON-RPC 2 is specified in terms of. You can't get much more agnostic than that.

> About JSON-RPC 2.0 being hard to use over HTTP, why? Since 2.0 there is a clear client-server separation, meaning that every client->server message will cause exactly 0 or 1 server->client messages. Isn't that exactly how HTTP works?

As I said above, HTTP has no means of providing no response to a request. It also uses a different mechanism for associating requests with responses than JSON-RPC 2, and those two mechanisms need to be reconciled somehow. It's certainly possible to reconcile them, but the spec provides no guidance here which means that any choice we make may be incompatible with other endpoints. It should be left up to the user to determine how that translation works.

**Comment by stevenroose** [comment]
I still don't get why this library does not support creating a client using a `http.Client` instead of a websocket.

**Comment by kylegoetz** [comment]
Miniflux is an example of a JSON RPC compliant server that communicates over HTTP rather than WS. Can you recommend how I would use this library to communicate with it? As mentioned by someone else above, the example is only for Websockets, and I can't figure out how to use this library to work with HTTP.

You can contrast with this library that provides an example showing it works with HTTP. https://github.com/jwashin/jsonrpc2-dart

Any thoughts? I realize this issue was closed over a year ago, but I didn't want to open a new one to ask this question.

**Comment by nex3** [comment]
What I said before is still true:

> HTTP has no means of providing no response to a request. It also uses a different mechanism for associating requests with responses than JSON-RPC 2, and those two mechanisms need to be reconciled somehow. It's certainly possible to reconcile them, but the spec provides no guidance here which means that any choice we make may be incompatible with other endpoints. It should be left up to the user to determine how that translation works.

You can implement your own `StreamChannel` on top of an HTTP client that decides how to answer these questions, but it's not the place of this package to have an opinion on the matter.

Also, as far as I can tell, Miniflux doesn't use JSON-RPC 2.0. Among other things, [its API docs](https://docs.miniflux.net/en/latest/api.html) don't include the `"json-rpc": "2.0"` key/value pair that identifies the protocol.

**Comment by spookyuser** [comment]
Reading through this thread, it is a pity that this library ultimately decided not to support JSON-RPC 2 via HTTP.

As an example of a JSON-RPC 2 compliant application that does not use websockets see [here](https://openwrt.org/docs/techref/ubus#access_to_ubus_over_http).

It would be quite helpful, I think, to write that this library only works with web sockets, in the readme. It wasn't obvious to me that this was the case, and took me a while to find this closed issue.

**Comment by natebosch** [comment]
> It would be quite helpful, I think, to write that this library only works with web sockets, in the readme.

It works over any `StreamChannel<String>`. Web sockets is the common case, but not the only case. Using stdio is another common use, and I think I've seen SSE used as well.

You could write a wrapper around an http client to make it look like a `StreamChannel<String>` that works with the `Client` class here. Unfortunately I don't see a good way to write a `Server` or a `Peer` this way assuming that the clients would require that a given response is exactly the reply to the corresponding request. If you want to try this you'd write a `StreamChannel` where the `sink` drops a request onto an http client, and when the response is received forwards it along through the channels `stream`.

> is a pity that this library ultimately decided not to support JSON-RPC 2 via HTTP.

It is not feasible or sensible for us to write an implementation that takes an HTTP client, or HTTP server, since we don't know the specifics of how they should be used. For example deciding between POST or GET, deciding the specific URLs to use, deciding whether there is any specific encoding that needs to happen on the wire, etc.

What we could potentially do is write the constructors `Server(Stream<void Function(String)>)`, `Client(FutureOr<String> Function(String))`, `Peer(Stream<void Function(String)>, FutureOr<String> Function(String))`.

`Stream<void Function(String)>` could be built on top of an http server, and `FutureOr<String> Function(String)` could be build on top of an http client.

Since the `Client` use case seems to be what people are after, and that _can_ be supported already by wrapping up an http client as a `StreamChannel<String>`, I'm not sure it's worth trying to add new constructors to support the `Server` use case.

**Comment by gpasq** [comment]
Took me a while to get to this issue.  I too find it strange that you won't support jsonrpc over http, especially with the claim that it's "non standard".  Yet all of the other client libs I use support jsonrpc over http with no issue.

At least document this problem in the readme.  Just wasted an hour of my time.

**Comment by deimantasa** [comment]
BUMPing for hope that this will be implemented. As an alternative solution - [this](https://pub.dev/packages/jsonrpc2) works. However, it'd be great to have official JSON RPC 2.0 implementation for HTTPS.

**Comment by lesnitsky** [comment]
Here's an example of how you could use this package over http:

```dart
import 'package:json_rpc_2/json_rpc_2.dart';
import 'package:stream_channel/stream_channel.dart';
import 'package:http/http.dart' as http;

StreamChannel<String> createHttpChannel(Uri uri) {
  final client = http.Client();
  final responses = StreamController<String>.broadcast();
  final requests = StreamController<String>();

  const headers = {'Content-Type': 'application/json'};

  requests.stream.listen((event) async {
    try {
      final res = await client.post(uri, body: event, headers: headers);
      responses.add(res.body);
    } catch (e) {
      responses.addError(e);
    }
  });

  return StreamChannel.withGuarantees(responses.stream, requests);
}

final channel = createHttpChannel(Uri.parse('http://localhost:4040/json-rpc'));
final rpcClient = Client(channel)..listen();
```

**Comment by natebosch** [comment]
> especially with the claim that it's "non standard".

I'm not familiar with any specification for a standard way to set up JSON RPC over HTTP. Can you share a link to a standard if you know of one you'd like us to support?

> Yet all of the other client libs I use support jsonrpc over http with no issue.

To be clear - JSON RPC over HTTP is not specifically _blocked_ by this package. This package is intentionally transport agnostic. You should be able to implement any transport details you'd like, and plug in to this package.
