### ISSUE TITLE
Does not report (method not found) back to client

### ISSUE THREAD

**Issue by dnfield** [dart-lang/json_rpc_2#40]
See https://github.com/flutter/flutter/issues/31813

When the server can't find a method definition in at least some cases, it doesn't report back to the client - this exception instead is unhandled (and piped back to anyone who registered to be notified on unhandled exceptions).  This appears to be happening when clients connect to Flutter's VM Service before it has fully initialized (e.g. the observatory URL publishes, someone tries to call a method on it, and the server crashes because it doesn't have any methods available).

It would be nice if the server instead reported back to the client that the method was not found in this case.

**Comment by dnfield** [comment]
@kevmoo @natebosch @jacob314 - is there someone from the Dart side who will be able to investigate this?  I can attempt a patch at some point, but it will take some time for me to be able to get to it.

**Comment by kevmoo** [comment]
@mit-mit @athomas ?

**Comment by dnfield** [comment]
Looked at the spec a bit more for this - this is apparently by design.  In this case, a notification is sent to the server and the spec says the server must not send a response (see 4.1 of https://www.jsonrpc.org/specification).  

I'm not sure what, if any, changes make sense here in the package.  On the Flutter side, we should probably either avoid using notifications and potentially screen for these exceptions in our error handlers.  It _might_ be useful to have the package give some indication in the error callback about this, but I'm not really sure.

**Comment by dnfield** [comment]
We're going to fix this on the consumer side.
