### ISSUE TITLE
Operation timed out

### ISSUE THREAD

**Issue by bordunosp** [dart-lang/json_rpc_2#63]
if I run example code
have some error "Operation timed out"

<pre>
WebSocketChannelException: WebSocketChannelException: SocketException: OS Error: Operation timed out, errno = 60, address = 127.0.0.2, port = 53813
#0      new IOWebSocketChannel._withoutSocket.<anonymous closure> (package:web_socket_channel/io.dart:84:24)
#1      _invokeErrorHandler (dart:async/async_error.dart:19:29)
#2      _HandleErrorStream._handleError (dart:async/stream_pipe.dart:288:9)
#3      _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:170:13)
#4      _RootZone.runBinaryGuarded (dart:async/zone.dart:1328:10)
#5      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:357:15)
#6      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:375:16)
#7      _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:274:7)
#8      _SyncStreamControllerDispatch._sendError (dart:async/stream_controller.dart:770:19)
#9      _StreamController._addError (dart:async/stream_controller.dart:650:7)
#10     _RootZone.runBinaryGuarded (dart:async/zone.dart:1328:10)
#11     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:357:15)
#12     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:375:16)
#13     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:274:7)
#14     _SyncStreamControllerDispatch._sendError (dart:async/stream_controller.dart:770:19)
#15     _StreamController._addError (dart:async/stream_controller.dart:650:7)
#16     new Stream.fromFuture.<anonymous closure> (dart:async/stream.dart:177:18)
#17     _RootZone.runBinary (dart:async/zone.dart:1386:54)
#18     _FutureListener.handleError (dart:async/future_impl.dart:153:20)
#19     Future._propagateToListeners.handleError (dart:async/future_impl.dart:692:47)
#20     Future._propagateToListeners (dart:async/future_impl.dart:713:24)
#21     Future._completeError (dart:async/future_impl.dart:532:5)
#22     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:580:7)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
</pre>

**Comment by natebosch** [comment]
Looks like you don't have a server listening on those ports - the example code are not intended to be full examples that can be run in isolation. The examples are intended to show the API usage.
