### ISSUE TITLE
Provide an example using WebSocket from dart:html

### ISSUE THREAD

**Issue by rwl** [dart-lang/json_rpc_2#8]
The README currently includes an example of how to use `json_rpc_2` with `WebSocket` from `dart:io`.  However, the `WebSocket` class from `dart:html` seems to have a slightly different API.  It would be great if the documentation included an example of how to use the client within a browser.  Currently, I am using this code, but I suspect that I am missing a trick or two:

```dart
var socket = new WebSocket(url);
socket.onOpen.listen((_) {
  var requests = new StreamController<String>();
  requests.stream.listen((data) => socket.send(data));
  var client = new rpc.Client(new StreamChannel(
    socket.onMessage.map((evt) => evt.data), requests));
});
```

**Comment by nex3** [comment]
Well, first of all, you should use a [`StreamChannelController`](https://www.dartdocs.org/documentation/stream_channel/1.3.1/stream_channel/StreamChannelController-class.html) to ensure that your custom channel follows the stream channel rules.

I'd rather not force everyone to do that manually, though. I'll think about where a good place would be to put a standard implementation. Once we have that, I'll link to it in the docs.
