### ISSUE TITLE
How to send acknowledgments

### ISSUE THREAD

**Issue by R0m4in-dooz** [dart-lang/json_rpc_2#81]
Hello, thx for this lib !

I'm currently working on some communication between a phone and iot device using JSON RPC over WSS thanks to your lib.
I would need to send back a null response for some specific registered method.
See below code :
```dart
_peer.registerMethod(
  'my_method',
  (Parameters parameters) {
    // do stuff
    return null;
  },
);
```
I would like that the I/O on socket would be something like this:
```json
// received
{
  "jsonrpc": "2.0", 
  "method": "my_method", 
  "params": {
    [...]
  }, 
  "id": "9f07bfae-0de3-49a0-9d2b-43e9e90c5147"
}
// answered
{
   "jsonrpc": "2.0", 
   "id": "9f07bfae-0de3-49a0-9d2b-43e9e90c5147", 
   "result": null
}
```
Notice how the IDs should be the same.

Is it possible to do so with the lib? I tried the `return null`, but it seems it's not enough.

Thanks,
R0m4in

**Comment by natebosch** [comment]
> I tried the `return null`, but it seems it's not enough.

Yes, returning `null` from the handler will include a response like your example, including responding with exactly the same `id` as it was given.

This test for this behavior is: https://github.com/dart-lang/json_rpc_2/blob/f46a5ff650dc318d359eb7fff465638848c6a5ed/test/server/server_test.dart#L47-L54

**Comment by R0m4in-dooz** [comment]
Oh ok, perfect then !
I guess I should have double checked my code first before asking lol 
Thank you @natebosch 🙏🏻
